### ISSUE TITLE
Dolthub Swiss Benchmark Comparision

### ISSUE THREAD

**Issue by mhmtszr** [cockroachdb/swiss#19]
We actively use Dolthub Swiss Map https://github.com/dolthub/swiss. Have you ever compared the performance and features with the swiss implementation of this library? Why should we switch to cockroachdb/swiss? According to a small benchmark test I did, cockroachdb/swiss makes less heap allocation.

**Comment by petermattis** [comment]
Sorry for the (long) delay in responding. I haven't benchmarked the Dolthub Swiss Map implementation since the very earliest days of this project. There are some numbers in https://github.com/cockroachdb/swiss/commit/f0cdd7fac898ac3e7ad9effa9c9d0457d512cb65:

```
The inspiration behind writing a Go implementation of Swiss Tables came from
https://github.com/dolthub/swiss. That implementation is quite a bit slower
and does not follow the original design (the slots are divided into groups
which do not overlap).

name                        old time/op  new time/op  delta
StringMaps/n=16/map-10      11.2ns ±15%   7.3ns ± 1%  -34.24%  (p=0.000 n=10+8)
StringMaps/n=128/map-10     12.2ns ±10%   7.4ns ± 4%  -38.76%  (p=0.000 n=10+10)
StringMaps/n=1024/map-10    12.7ns ± 5%   7.5ns ± 2%  -40.65%  (p=0.000 n=10+10)
StringMaps/n=8192/map-10    14.3ns ± 3%   7.9ns ± 1%  -44.87%  (p=0.000 n=10+10)
StringMaps/n=131072/map-10  18.5ns ± 2%  13.9ns ± 2%  -24.86%  (p=0.000 n=10+8)
Int64Maps/n=16/map-10       6.26ns ±17%  4.85ns ± 1%  -22.47%  (p=0.000 n=10+8)
Int64Maps/n=128/map-10      6.76ns ± 4%  4.99ns ± 0%  -26.20%  (p=0.001 n=8+6)
Int64Maps/n=1024/map-10     7.07ns ± 3%  4.97ns ± 2%  -29.71%  (p=0.000 n=10+10)
Int64Maps/n=8192/map-10     8.52ns ± 5%  5.30ns ± 1%  -37.77%  (p=0.000 n=10+10)
Int64Maps/n=131072/map-10   12.0ns ± 2%   6.7ns ± 1%  -44.11%  (p=0.000 n=10+10)
```

My recollection is that the Dolthub implementation did not adhere closely to the Abseil implementation. `cockroachdb/swiss` does. Note also that Go folks are experimenting with replacing the Go map implementation with one inspired by this Swiss table implementation. Follow along in https://github.com/golang/go/issues/54766. I'm not sure when that will land. Go 1.24? Go 1.25?
